Ft edit company
mwafrika/shift-plan-backend pull request #10
Opened 2023-10-11 14:32 UTC by Irirwanirira

## This Pr consist of: 

- [ ] Update companies.

### Thanks.

2023-10-19 07:15 UTC, alainburindi requested changes

2023-10-19 07:15 UTC, alainburindi commented on src/controllers/company.js
> +  console.log(oldCompany.id);
The console.log is not needed

2023-10-19 07:15 UTC, alainburindi commented on src/controllers/auth.js
> +    // roleId,
remove commented codes

2023-10-20 05:24 UTC, mwafrika approved these changes

2023-10-20 07:06 UTC, jefftrojan approved these changes

2023-11-16 05:10 UTC, closed without merging