Ft code improvement
mwafrika/shift-plan-backend pull request #20
Opened 2023-10-24 13:50 UTC by mwafrika

- Improved the logic based on the feedback
- Add account verification
- Add reset password template
- Modified relationship in shifts(from one-to-to to many-to-many) relationship

2023-10-24 14:30 UTC, Irirwanirira requested changes

2023-10-24 14:30 UTC, Irirwanirira commented on src/controllers/auth.js
> +  console.log(req.user, "req.user xxxxxxxx");
remove console.log from your codebase

2023-10-24 14:30 UTC, Irirwanirira commented on src/controllers/shift.js
> +    // }
remove commented codes

2023-10-24 14:30 UTC, Irirwanirira commented on src/database/models/user.js
> +      // });
same here

2023-10-24 14:46 UTC, Irirwanirira approved these changes
Good to go!

2023-11-02 09:07 UTC, jefftrojan approved these changes

2023-11-16 05:07 UTC, merged