Create user and company
mwafrika/shift-plan-backend pull request #4
Opened 2023-10-10 17:51 UTC by mwafrika

# What does this pull do ?

- [ ] Create a user
- [ ] Create a company

2023-10-10 18:14 UTC, jefftrojan commented
2 checks failed though, did you see that?

2023-10-11 10:46 UTC, ciraganenicole approved these changes

2023-10-12 13:35 UTC, Irirwanirira approved these changes

2023-10-12 13:59 UTC, alainburindi requested changes

2023-10-12 13:59 UTC, alainburindi commented on src/config/database.js
>  dotenv.config();
dotenv should be configured only once. In the app.js maybe

2023-10-12 13:59 UTC, alainburindi commented on src/config/database.js
> +    host: 'localhost',
This one can also be put in the environment variables

2023-10-12 13:59 UTC, alainburindi commented on src/controllers/auth.js
> +    // roleId,
Kindy remove commented codes

2023-10-12 13:59 UTC, alainburindi commented on src/database/models/company.js
> +        // onUpdate: "CASCADE",
Same here

2023-10-12 13:59 UTC, alainburindi commented on src/utils/auth.js
> +};
Not used so far

2023-10-12 13:59 UTC, alainburindi commented on src/utils/format.js
> +  const successMessage = 'Success';
```suggestion
  const message = errorMessage || 'Success';
```

2023-10-12 13:59 UTC, alainburindi commented on src/utils/format.js
> +    message: errorMessage || successMessage,
```suggestion
    message,
```

2023-10-12 14:28 UTC, alainburindi approved these changes

2023-10-12 14:28 UTC, merged