Ft list users
mwafrika/shift-plan-backend pull request #6
Opened 2023-10-11 09:51 UTC by Irirwanirira

### ThIS pr consists of: 

- [ ] Fetching a list of all users from the database.

2023-10-11 10:47 UTC, ciraganenicole approved these changes

2023-10-17 07:04 UTC, alainburindi requested changes

2023-10-17 07:04 UTC, alainburindi commented on src/database/models/index.js
> +"use strict";
What's the reason behind this line?

2023-10-19 07:06 UTC, alainburindi approved these changes

2023-10-19 07:06 UTC, alainburindi commented
Kindly rebase to fix the conflicts

2023-10-20 06:27 UTC, mwafrika approved these changes

2023-11-16 05:10 UTC, closed without merging